# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ed6e0ff5b338bbc71e60dc1e49857a5d"
name = "vogo-custom-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true
handle = "vogo-custom-app"

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_cart_transforms,write_discounts,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
